server:
  port: 8082

spring:
  timezone: Asia/Kolkata
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296 
  output:
    ansi:
      enabled: always
      
resilience4j:
  circuitbreaker:
    instances:
      external:
         event-consumer-buffer-size: 10
         failure-rate-threshold: 50
         minimum-number-of-calls: 5
         automatic-transition-from-open-to-half-open-enabled: true
         wait-duration-in-open-state: 5s
         permitted-number-of-calls-in-half-open-state: 3
         sliding-window-size: 10
         sliding-window-type: COUNT_BASED
  
logging:
    level:
      org:
        springframework:
          cloud:
            config: INFO
          web:
            servlet:
              DispatcherServlet: INFO
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        greeting: true
      
#erueka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true 
#    fetch-registry: true
#    service-url:
#      default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    
    

